/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthorizedRouteImport } from './routes/_authorized'
import { Route as AuthorizedCalendarIndexRouteImport } from './routes/_authorized/calendar/index'
import { Route as AuthorizedHomeIndexRouteImport } from './routes/_authorized/home/index'
import { Route as AuthorizedProjectsIndexRouteImport } from './routes/_authorized/projects/index'
import { Route as AuthorizedTasksIndexRouteImport } from './routes/_authorized/tasks/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorizedRoute = AuthorizedRouteImport.update({
  id: '/_authorized',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorizedCalendarIndexRoute = AuthorizedCalendarIndexRouteImport.update({
  id: '/calendar/',
  path: '/calendar/',
  getParentRoute: () => AuthorizedRoute,
} as any)
const AuthorizedHomeIndexRoute = AuthorizedHomeIndexRouteImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => AuthorizedRoute,
} as any)
const AuthorizedProjectsIndexRoute = AuthorizedProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AuthorizedRoute,
} as any)
const AuthorizedTasksIndexRoute = AuthorizedTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AuthorizedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar/': typeof AuthorizedCalendarIndexRoute
  '/home/': typeof AuthorizedHomeIndexRoute
  '/projects/': typeof AuthorizedProjectsIndexRoute
  '/tasks/': typeof AuthorizedTasksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof AuthorizedCalendarIndexRoute
  '/home': typeof AuthorizedHomeIndexRoute
  '/projects': typeof AuthorizedProjectsIndexRoute
  '/tasks': typeof AuthorizedTasksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authorized': typeof AuthorizedRouteWithChildren
  '/_authorized/calendar/': typeof AuthorizedCalendarIndexRoute
  '/_authorized/home/': typeof AuthorizedHomeIndexRoute
  '/_authorized/projects/': typeof AuthorizedProjectsIndexRoute
  '/_authorized/tasks/': typeof AuthorizedTasksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/calendar/' | '/home/' | '/projects/' | '/tasks/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/calendar' | '/home' | '/projects' | '/tasks'
  id:
    | '__root__'
    | '/'
    | '/_authorized'
    | '/_authorized/calendar/'
    | '/_authorized/home/'
    | '/_authorized/projects/'
    | '/_authorized/tasks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthorizedRoute: typeof AuthorizedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authorized': {
      id: '/_authorized'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authorized/calendar/': {
      id: '/_authorized/calendar/'
      path: '/calendar'
      fullPath: '/calendar/'
      preLoaderRoute: typeof AuthorizedCalendarIndexRouteImport
      parentRoute: typeof AuthorizedRoute
    }
    '/_authorized/home/': {
      id: '/_authorized/home/'
      path: '/home'
      fullPath: '/home/'
      preLoaderRoute: typeof AuthorizedHomeIndexRouteImport
      parentRoute: typeof AuthorizedRoute
    }
    '/_authorized/projects/': {
      id: '/_authorized/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AuthorizedProjectsIndexRouteImport
      parentRoute: typeof AuthorizedRoute
    }
    '/_authorized/tasks/': {
      id: '/_authorized/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof AuthorizedTasksIndexRouteImport
      parentRoute: typeof AuthorizedRoute
    }
  }
}

interface AuthorizedRouteChildren {
  AuthorizedCalendarIndexRoute: typeof AuthorizedCalendarIndexRoute
  AuthorizedHomeIndexRoute: typeof AuthorizedHomeIndexRoute
  AuthorizedProjectsIndexRoute: typeof AuthorizedProjectsIndexRoute
  AuthorizedTasksIndexRoute: typeof AuthorizedTasksIndexRoute
}

const AuthorizedRouteChildren: AuthorizedRouteChildren = {
  AuthorizedCalendarIndexRoute: AuthorizedCalendarIndexRoute,
  AuthorizedHomeIndexRoute: AuthorizedHomeIndexRoute,
  AuthorizedProjectsIndexRoute: AuthorizedProjectsIndexRoute,
  AuthorizedTasksIndexRoute: AuthorizedTasksIndexRoute,
}

const AuthorizedRouteWithChildren = AuthorizedRoute._addFileChildren(
  AuthorizedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthorizedRoute: AuthorizedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
