/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthorizedRouteImport } from './routes/_authorized'
import { Route as AuthorizedHomeIndexRouteImport } from './routes/_authorized/home/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorizedRoute = AuthorizedRouteImport.update({
  id: '/_authorized',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorizedHomeIndexRoute = AuthorizedHomeIndexRouteImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => AuthorizedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/home/': typeof AuthorizedHomeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home': typeof AuthorizedHomeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authorized': typeof AuthorizedRouteWithChildren
  '/_authorized/home/': typeof AuthorizedHomeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/home/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/home'
  id: '__root__' | '/' | '/_authorized' | '/_authorized/home/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthorizedRoute: typeof AuthorizedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authorized': {
      id: '/_authorized'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authorized/home/': {
      id: '/_authorized/home/'
      path: '/home'
      fullPath: '/home/'
      preLoaderRoute: typeof AuthorizedHomeIndexRouteImport
      parentRoute: typeof AuthorizedRoute
    }
  }
}

interface AuthorizedRouteChildren {
  AuthorizedHomeIndexRoute: typeof AuthorizedHomeIndexRoute
}

const AuthorizedRouteChildren: AuthorizedRouteChildren = {
  AuthorizedHomeIndexRoute: AuthorizedHomeIndexRoute,
}

const AuthorizedRouteWithChildren = AuthorizedRoute._addFileChildren(
  AuthorizedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthorizedRoute: AuthorizedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
