export const tasks = [
  {
    id: 1,
    title: "Create wireframes",
    project: "Website Redesign",
    priority: "High",
    due: "Today",
    completed: true,
  },
  {
    id: 2,
    title: "Design homepage",
    project: "Website Redesign",
    priority: "Medium",
    due: "Tomorrow",
    completed: true,
  },
  {
    id: 3,
    title: "Implement authentication",
    project: "Website Redesign",
    priority: "High",
    due: "Sep 2",
    completed: false,
  },
  {
    id: 4,
    title: "Create database schema",
    project: "Task Manager",
    priority: "Medium",
    due: "Sep 4",
    completed: false,
  },
  {
    id: 5,
    title: "Deploy application",
    project: "Website Redesign",
    priority: "Low",
    due: "Sep 7",
    completed: false,
  },
];
